### ISSUE TITLE
Cannot Access "Persistent.shelve.db"

### ISSUE THREAD

**Issue by ckhajavi** [Mondego/crawler4py#7]
Hi, 
I am trying to read from the shelve but keep getting this error:
`import shelve`
`shelve.open("Persistent.shelve.db")`

---

Traceback (most recent call last):
  File "SampleCrawler.py", line 13, in <module>
    shelve.open("Persistent.shelve.db")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 223, in **init**
    Shelf.**init**(self, anydbm.open(filename, flag), protocol, writeback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 82, in open
    raise error, "db type could not be determined"
anydbm.error: db type could not be determined

**Comment by rohan-achar** [comment]
If you are using a different version of python or OS other than the one used to create it, that could be a problem.

If not seems like you caught this bug https://bugs.python.org/issue23174
